### ISSUE TITLE
Is posible check if a number phone have whatsapp?

### ISSUE THREAD

**Issue by webserveis** [omegaes/Whatsapp-API#1]
Recently whatsapp add feature in link, start chat without add contact in contacts database, using direct link

`https://api.whatsapp.com/send?phone=XXXXXXXX`

is posible check if the phone have a whatsapp?

**Comment by omegaes** [comment]
I don't think it is possible, this link need authentication

**Comment by nian88** [comment]
@omegaes when I try this library why the error to open the wa database

**Comment by omegaes** [comment]
@nian88  can you attach your logcat history ? wa database contains your whatsapp contacts

**Comment by nian88** [comment]
this my logcat history 

![image](https://cloud.githubusercontent.com/assets/18239536/24852293/2720f01a-1e01-11e7-86b3-c4a15dbcec91.png)

**Comment by omegaes** [comment]
@nian88 Are you sure your device is rooted and grant your application root privileges and have Whatsaap application, not whatsapp plus  or whatever ?!?

**Comment by nian88** [comment]
yes my device is rooted..I try on a different device but experiencing the same problem

this my project https://github.com/nian88/wanian

**Comment by JavierSolis** [comment]
I had the same problem, check your builder, and add this line

`Shell.SU.run("chmod 777 /data/data/com.whatsapp/databases/wa.db");
`
And solved.
I hope it helps you.

**Comment by omegaes** [comment]
@JavierSolis you are right, I will use
        
Shell.SU.run("chmod -R 777 /data/data/com.whatsapp");
this one will solve all issues

**Comment by JavierSolis** [comment]
@webserveis to check if the number has whastapp, you could add it to your contacts, after a moment and if there is internet, check the list of users

`WhatsappApi.getInstance().getContacts(Context, GetContactsListener)`

**Comment by nian88** [comment]
@JavierSolis @omegaes  awesome.. thanks.. solved
