### ISSUE TITLE
Version 1.0.4

### ISSUE THREAD

**Issue by ajaybhatt17** [omegaes/Whatsapp-API#15]
@omegaes : Can you let me know the pr i submitted and you have merged .. did it hv any issues bcz of which u retract it.

**Comment by omegaes** [comment]
1.0.4 has some issues, changes made just for lib module, app module didn't get any updates so that cause a compile error and jitpack wasn't able to build the library

**Comment by ajaybhatt17** [comment]
@omegaes Okay .. let me create new pr in sometime considering changes in app module along with lib module. Thanks for reply.
