### ISSUE TITLE
Database contacts getting error

### ISSUE THREAD

**Issue by mudassirzulfiqar** [omegaes/Whatsapp-API#2]
Hi My phone is rooted. Im just testing this project. I got an error at this line

                                     db = SQLiteDatabase.openOrCreateDatabase(new File("/data/data/com.whatsapp/databases/wa.db"), null);
while getting contacts. Can you please elaborate this error. Also I havnt found any directory named wa.db in my phone. ??

**Comment by rodrigoxcruz** [comment]
The same problem happened to me. Any solution?

**Comment by mudassirzulfiqar** [comment]
Im trying to figure this out.. I think developer should address this issue

**Comment by muhammadkamranlatifraza** [comment]
I have tried to getContacts(); this is showing me 

                                                                      Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14): , while compiling: PRAGMA journal_mode

**Comment by omegaes** [comment]
Hi, I published new update, it gonna save the problem, give it a try

**Comment by TazmanOne** [comment]
If you had problem you need add permission on main folder
Shell.SU.run("chmod 777 /data/data/com.whatsapp");
