### ISSUE TITLE
can I send a message to an unknown number?

### ISSUE THREAD

**Issue by kishansinhparmar** [omegaes/Whatsapp-API#8]

**Comment by Babar-Bashir** [comment]
Yes

**Comment by nooballday** [comment]
@Babar-Bashir how do we do that ? the sendMessage method takes WContact object to determine the receiver.

**Comment by kishansinhparmar** [comment]
Okay, now I send a message to an unknown person using...
new WContact("PersonNmae", "91xxxxxxxxxx@s.whatsapp.net")

**Comment by poornimasivakumar** [comment]
@kishansinhparmar  where did you do this?
